[colors]
[colors.primary]
background = '#02098A'
foreground = '#C2C2C2'

[colors.selection]
text = '#C2C2C2'
background = '#4C566A'

# Normal colors (Maintained standard syntax colors for readability)
[colors.normal]
black = '#434C5E'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#BFBDBD'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#C2C2C2'

# Bright colors
[colors.bright]
black = '#4C566A'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#ffffff'
